# Dockerfile final
FROM ubuntu:22.04
RUN apt-get update && apt-get install -y renode gpsd i2c-tools
COPY vΩ4-digital-twin.repl /opt/
COPY sur73_predictor /opt/
CMD ["renode", "/opt/vΩ4-digital-twin.repl"]